name: Auto Rebase Dev on Main

on:
  push:
    branches:
      - main

jobs:
  rebase-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: dev
          fetch-depth: 0
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name 'GitHub bot rebase main'
          git config user.email 'action@github.com'

      - name: Rebase dev on main
        run: |
          git fetch origin main
          git rebase origin/main
          git push https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/IBRAHIMDANS/thruid.git dev

      - name: Clean up
        if: always()
        run: git rebase --abort
